language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - CODECOV_TOKEN="18735e90-ad9e-447f-bba9-7846bc08170f"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake openssl libssl-dev lcov

install:
  - ./prepare.sh

script:
  - ./travis_build.sh
