matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake openssl libssl-dev lcov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - ./prepare.sh

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1 ../
  - make -j2 raft_cov

after_script:
  - ./cc-test-reporter format-coverage -t lcov ./raft_cov.info.cleaned
  - ./cc-test-reporter upload-coverage
